---
services: docker

env:
  - distro: centos7
    playbook: test.yml
    prefix: ''
    http_port: 8080

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x tests/test.sh

  # Run tests.
  - tests/test.sh

 # Make sure Alfresco is running.
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://localhost:$http_port/$prefix'

after_failure:
  # Check what happened on systemd systems.   
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl -l status alfresco.service'
  - 'docker exec --tty ${container_id} env TERM=xterm journalctl -xe --no-pager'

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/