- name: Download mysql-java-connector
  shell: 'wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
      -O /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz creates=/tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz'
  register: mysqlconnector_downloaded

- name: Extract mysql-java-connector
  shell: 'tar xzf /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz -C /tmp'
  register: mysqlconnector_extracted
  when: mysqlconnector_downloaded|changed

- name: Install mysql-java-connector
  shell: 'mv /tmp/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar {{ tomcat_dir }}/lib/ && chown {{ alfresco_user }}:{{ alfresco_group }} {{ tomcat_dir }}/lib/mysql-connector-java-{{ mysql_connector_version }}-bin.jar'
  when: mysqlconnector_extracted|changed

- name: Cleanup mysql-java-connector
  shell: 'rm -rf /tmp/mysql-connector-java-{{ mysql_connector_version }}'
  when: mysqlconnector_extracted|changed

- name: Configure transaction isolation
  lineinfile: dest=/etc/my.cnf insertafter="sql-mode" line="transaction-isolation=READ-COMMITTED"